### ISSUE TITLE
Update helm charts to use Rafiki version v1.0.0-alpah.3

### ISSUE THREAD

**Issue by sabineschaller** [interledger/helm-charts#10]

**Comment by rashmibharambe** [comment]
@sabineschaller can you assign this to me, I can work on this.
Also pls confirm version - looks to be incorrectly spelled in title.

**Comment by sabineschaller** [comment]
Thank you for taking this one @rashmibharambe!

**Comment by rashmibharambe** [comment]
> Thank you for taking this one @rashmibharambe!

I have raised a PR, please check and let me know if any modifications. 
https://github.com/interledger/helm-charts/pull/15
