### ISSUE TITLE
Improve helm charts

### ISSUE THREAD

**Issue by sabineschaller** [interledger/helm-charts#11]
There is a lot of recursion in our helm charts. Improve templating. Any other improvements also welcome.

**Comment by ShatilKhan** [comment]
Hey can I please work on this?
Please assign me this issue

**Comment by ShatilKhan** [comment]
It would be great to have some additional information

**Comment by sabineschaller** [comment]
@ShatilKhan go for it! 
The templates of our three helm charts basically all look the same and there is a lot of copy pasting happening from one to the other. Now I'm not an expert on this by any means but I know that you can basically create a "base chart" and then derive the other three from that one. 
But like I said, any improvements are welcome. I just made them work back in the days.
