### ISSUE TITLE
Create a contribution guide

### ISSUE THREAD

**Issue by devcer** [interledger/helm-charts#12]
* Use the [rafiki](https://github.com/interledger/rafiki/blob/main/.github/contributing.md) repository as a base and create a contribution guide for this repository

@sabineschaller Please add hacktoberfest tag to this issue.

**Comment by dev31sanghvi** [comment]
I am working on it ! @sabineschaller

**Comment by devcer** [comment]
This is all your's. All the best @dev31sanghvi

**Comment by dev31sanghvi** [comment]
@devcer  hey , i need write access as i don't have access to push changes.

**Comment by devcer** [comment]
@dev31sanghvi You will have to fork the repository, push your code to your fork and submit a pull request for this repository. Give [this](https://community.interledger.org/devcer/git-hacks-for-hacktoberfest-a-quick-and-easy-guide-43jb) a read to understand more

**Comment by dev31sanghvi** [comment]
Got it ! Thank you so much for your help.
