### ISSUE TITLE
Enhance README.md with Emojis for Clarity

### ISSUE THREAD

**Issue by SOBANEJAZ** [interledger/helm-charts#9]
""Issue Description"":
I would like to contribute to this repository by enhancing the README.md for improved clarity and aesthetics. My suggestion is to add emojis to the existing headings in the README to make it more visually appealing and user-friendly.

Proposed Emojis for Headings:

1. ""Usage ""💡
2. ""Contributing"" 🤝
3. ""License"" 📝
I believe that adding emojis to the headings will not only make the documentation more engaging but also help readers quickly identify and understand the content of each section.

""Please assign this issue to me for the hacktoberfest. :)""

**Comment by sabineschaller** [comment]
We don't look to improve our README at the moment. If you would like to contribute, feel free to take 
- #10
